package Model;

/**
 * Created by IntelliJ IDEA.
 * User: Brunol
 * Date: 20/05/2010
 * Time: 09:47:04
 * To change this template use File | Settings | File Templates.
 */
public enum SubTitleLanguage {
    @CodeISO639_2("jav")
    @CodeISO639_1("jv")
    @Description("Javanese")
    jav,
    @CodeISO639_2("aar")
    @CodeISO639_1("aa")
    @Description("Afar, afar")
    aar,
    @CodeISO639_2("abk")
    @CodeISO639_1("ab")
    @Description("Abkhazian")
    abk,
    @CodeISO639_2("afr")
    @CodeISO639_1("af")
    @Description("Afrikaans")
    afr,
    @CodeISO639_2("aka")
    @CodeISO639_1("ak")
    @Description("Akan")
    aka,
    @CodeISO639_2("alb")
    @CodeISO639_1("sq")
    @Description("Albanian")
    alb,
    @CodeISO639_2("amh")
    @CodeISO639_1("am")
    @Description("Amharic")
    amh,
    @CodeISO639_2("ara")
    @CodeISO639_1("ar")
    @Description("Arabic")
    ara,
    @CodeISO639_2("arg")
    @CodeISO639_1("an")
    @Description("Aragonese")
    arg,
    @CodeISO639_2("arm")
    @CodeISO639_1("hy")
    @Description("Armenian")
    arm,
    @CodeISO639_2("asm")
    @CodeISO639_1("as")
    @Description("Assamese")
    asm,
    @CodeISO639_2("ava")
    @CodeISO639_1("av")
    @Description("Avaric")
    ava,
    @CodeISO639_2("ave")
    @CodeISO639_1("ae")
    @Description("Avestan")
    ave,
    @CodeISO639_2("aym")
    @CodeISO639_1("ay")
    @Description("Aymara")
    aym,
    @CodeISO639_2("aze")
    @CodeISO639_1("az")
    @Description("Azerbaijani")
    aze,
    @CodeISO639_2("bak")
    @CodeISO639_1("ba")
    @Description("Bashkir")
    bak,
    @CodeISO639_2("bam")
    @CodeISO639_1("bm")
    @Description("Bambara")
    bam,
    @CodeISO639_2("baq")
    @CodeISO639_1("eu")
    @Description("Basque")
    baq,
    @CodeISO639_2("bel")
    @CodeISO639_1("be")
    @Description("Belarusian")
    bel,
    @CodeISO639_2("ben")
    @CodeISO639_1("bn")
    @Description("Bengali")
    ben,
    @CodeISO639_2("bih")
    @CodeISO639_1("bh")
    @Description("Bihari")
    bih,
    @CodeISO639_2("bis")
    @CodeISO639_1("bi")
    @Description("Bislama")
    bis,
    @CodeISO639_2("bos")
    @CodeISO639_1("bs")
    @Description("Bosnian")
    bos,
    @CodeISO639_2("bre")
    @CodeISO639_1("br")
    @Description("Breton")
    bre,
    @CodeISO639_2("bul")
    @CodeISO639_1("bg")
    @Description("Bulgarian")
    bul,
    @CodeISO639_2("bur")
    @CodeISO639_1("my")
    @Description("Burmese")
    bur,
    @CodeISO639_2("cat")
    @CodeISO639_1("ca")
    @Description("Catalan")
    cat,
    @CodeISO639_2("cha")
    @CodeISO639_1("ch")
    @Description("Chamorro")
    cha,
    @CodeISO639_2("che")
    @CodeISO639_1("ce")
    @Description("Chechen")
    che,
    @CodeISO639_2("chi")
    @CodeISO639_1("zh")
    @Description("Chinese")
    chi,
    @CodeISO639_2("chu")
    @CodeISO639_1("cu")
    @Description("Church Slavic")
    chu,
    @CodeISO639_2("chv")
    @CodeISO639_1("cv")
    @Description("Chuvash")
    chv,
    @CodeISO639_2("cor")
    @CodeISO639_1("kw")
    @Description("Cornish")
    cor,
    @CodeISO639_2("cos")
    @CodeISO639_1("co")
    @Description("Corsican")
    cos,
    @CodeISO639_2("cre")
    @CodeISO639_1("cr")
    @Description("Cree")
    cre,
    @CodeISO639_2("cze")
    @CodeISO639_1("cs")
    @Description("Czech")
    cze,
    @CodeISO639_2("dan")
    @CodeISO639_1("da")
    @Description("Danish")
    dan,
    @CodeISO639_2("div")
    @CodeISO639_1("dv")
    @Description("Divehi")
    div,
    @CodeISO639_2("dut")
    @CodeISO639_1("nl")
    @Description("Dutch")
    dut,
    @CodeISO639_2("dzo")
    @CodeISO639_1("dz")
    @Description("Dzongkha")
    dzo,
    @CodeISO639_2("eng")
    @CodeISO639_1("en")
    @Description("English")
    eng,
    @CodeISO639_2("epo")
    @CodeISO639_1("eo")
    @Description("Esperanto")
    epo,
    @CodeISO639_2("est")
    @CodeISO639_1("et")
    @Description("Estonian")
    est,
    @CodeISO639_2("ewe")
    @CodeISO639_1("ee")
    @Description("Ewe")
    ewe,
    @CodeISO639_2("fao")
    @CodeISO639_1("fo")
    @Description("Faroese")
    fao,
    @CodeISO639_2("fij")
    @CodeISO639_1("fj")
    @Description("Fijian")
    fij,
    @CodeISO639_2("fin")
    @CodeISO639_1("fi")
    @Description("Finnish")
    fin,
    @CodeISO639_2("fre")
    @CodeISO639_1("fr")
    @Description("French")
    fre,
    @CodeISO639_2("fry")
    @CodeISO639_1("fy")
    @Description("Frisian")
    fry,
    @CodeISO639_2("ful")
    @CodeISO639_1("ff")
    @Description("Fulah")
    ful,
    @CodeISO639_2("geo")
    @CodeISO639_1("ka")
    @Description("Georgian")
    geo,
    @CodeISO639_2("ger")
    @CodeISO639_1("de")
    @Description("German")
    ger,
    @CodeISO639_2("gla")
    @CodeISO639_1("gd")
    @Description("Gaelic")
    gla,
    @CodeISO639_2("gle")
    @CodeISO639_1("ga")
    @Description("Irish")
    gle,
    @CodeISO639_2("glg")
    @CodeISO639_1("gl")
    @Description("Galician")
    glg,
    @CodeISO639_2("glv")
    @CodeISO639_1("gv")
    @Description("Manx")
    glv,
    @CodeISO639_2("ell")
    @CodeISO639_1("el")
    @Description("Greek")
    ell,
    @CodeISO639_2("grn")
    @CodeISO639_1("gn")
    @Description("Guarani")
    grn,
    @CodeISO639_2("guj")
    @CodeISO639_1("gu")
    @Description("Gujarati")
    guj,
    @CodeISO639_2("hat")
    @CodeISO639_1("ht")
    @Description("Haitian")
    hat,
    @CodeISO639_2("hau")
    @CodeISO639_1("ha")
    @Description("Hausa")
    hau,
    @CodeISO639_2("heb")
    @CodeISO639_1("he")
    @Description("Hebrew")
    heb,
    @CodeISO639_2("her")
    @CodeISO639_1("hz")
    @Description("Herero")
    her,
    @CodeISO639_2("hin")
    @CodeISO639_1("hi")
    @Description("Hindi")
    hin,
    @CodeISO639_2("hmo")
    @CodeISO639_1("ho")
    @Description("Hiri Motu")
    hmo,
    @CodeISO639_2("hrv")
    @CodeISO639_1("hr")
    @Description("Croatian")
    hrv,
    @CodeISO639_2("hun")
    @CodeISO639_1("hu")
    @Description("Hungarian")
    hun,
    @CodeISO639_2("ibo")
    @CodeISO639_1("ig")
    @Description("Igbo")
    ibo,
    @CodeISO639_2("ice")
    @CodeISO639_1("is")
    @Description("Icelandic")
    ice,
    @CodeISO639_2("ido")
    @CodeISO639_1("io")
    @Description("Ido")
    ido,
    @CodeISO639_2("iii")
    @CodeISO639_1("ii")
    @Description("Sichuan Yi")
    iii,
    @CodeISO639_2("iku")
    @CodeISO639_1("iu")
    @Description("Inuktitut")
    iku,
    @CodeISO639_2("ile")
    @CodeISO639_1("ie")
    @Description("Interlingue")
    ile,
    @CodeISO639_2("ina")
    @CodeISO639_1("ia")
    @Description("Interlingua (International Auxiliary Language Asso")
    ina,
    @CodeISO639_2("ind")
    @CodeISO639_1("id")
    @Description("Indonesian")
    ind,
    @CodeISO639_2("ita")
    @CodeISO639_1("it")
    @Description("Italian")
    ita,
    @CodeISO639_2("jpn")
    @CodeISO639_1("ja")
    @Description("Japanese")
    jpn,
    @CodeISO639_2("kal")
    @CodeISO639_1("kl")
    @Description("Kalaallisut")
    kal,
    @CodeISO639_2("kan")
    @CodeISO639_1("kn")
    @Description("Kannada")
    kan,
    @CodeISO639_2("kas")
    @CodeISO639_1("ks")
    @Description("Kashmiri")
    kas,
    @CodeISO639_2("kau")
    @CodeISO639_1("kr")
    @Description("Kanuri")
    kau,
    @CodeISO639_2("kaz")
    @CodeISO639_1("kk")
    @Description("Kazakh")
    kaz,
    @CodeISO639_2("khm")
    @CodeISO639_1("km")
    @Description("Khmer")
    khm,
    @CodeISO639_2("kik")
    @CodeISO639_1("ki")
    @Description("Kikuyu")
    kik,
    @CodeISO639_2("kin")
    @CodeISO639_1("rw")
    @Description("Kinyarwanda")
    kin,
    @CodeISO639_2("kir")
    @CodeISO639_1("ky")
    @Description("Kirghiz")
    kir,
    @CodeISO639_2("kom")
    @CodeISO639_1("kv")
    @Description("Komi")
    kom,
    @CodeISO639_2("kon")
    @CodeISO639_1("kg")
    @Description("Kongo")
    kon,
    @CodeISO639_2("kor")
    @CodeISO639_1("ko")
    @Description("Korean")
    kor,
    @CodeISO639_2("kua")
    @CodeISO639_1("kj")
    @Description("Kuanyama")
    kua,
    @CodeISO639_2("kur")
    @CodeISO639_1("ku")
    @Description("Kurdish")
    kur,
    @CodeISO639_2("lao")
    @CodeISO639_1("lo")
    @Description("Lao")
    lao,
    @CodeISO639_2("lat")
    @CodeISO639_1("la")
    @Description("Latin")
    lat,
    @CodeISO639_2("lav")
    @CodeISO639_1("lv")
    @Description("Latvian")
    lav,
    @CodeISO639_2("lim")
    @CodeISO639_1("li")
    @Description("Limburgan")
    lim,
    @CodeISO639_2("lin")
    @CodeISO639_1("ln")
    @Description("Lingala")
    lin,
    @CodeISO639_2("lit")
    @CodeISO639_1("lt")
    @Description("Lithuanian")
    lit,
    @CodeISO639_2("ltz")
    @CodeISO639_1("lb")
    @Description("Luxembourgish")
    ltz,
    @CodeISO639_2("lub")
    @CodeISO639_1("lu")
    @Description("Luba-Katanga")
    lub,
    @CodeISO639_2("lug")
    @CodeISO639_1("lg")
    @Description("Ganda")
    lug,
    @CodeISO639_2("mac")
    @CodeISO639_1("mk")
    @Description("Macedonian")
    mac,
    @CodeISO639_2("mah")
    @CodeISO639_1("mh")
    @Description("Marshallese")
    mah,
    @CodeISO639_2("mal")
    @CodeISO639_1("ml")
    @Description("Malayalam")
    mal,
    @CodeISO639_2("mao")
    @CodeISO639_1("mi")
    @Description("Maori")
    mao,
    @CodeISO639_2("mar")
    @CodeISO639_1("mr")
    @Description("Marathi")
    mar,
    @CodeISO639_2("may")
    @CodeISO639_1("ms")
    @Description("Malay")
    may,
    @CodeISO639_2("mlg")
    @CodeISO639_1("mg")
    @Description("Malagasy")
    mlg,
    @CodeISO639_2("mlt")
    @CodeISO639_1("mt")
    @Description("Maltese")
    mlt,
    @CodeISO639_2("mol")
    @CodeISO639_1("mo")
    @Description("Moldavian")
    mol,
    @CodeISO639_2("mon")
    @CodeISO639_1("mn")
    @Description("Mongolian")
    mon,
    @CodeISO639_2("nau")
    @CodeISO639_1("na")
    @Description("Nauru")
    nau,
    @CodeISO639_2("nav")
    @CodeISO639_1("nv")
    @Description("Navajo")
    nav,
    @CodeISO639_2("nbl")
    @CodeISO639_1("nr")
    @Description("Ndebele, South")
    nbl,
    @CodeISO639_2("nde")
    @CodeISO639_1("nd")
    @Description("Ndebele, North")
    nde,
    @CodeISO639_2("ndo")
    @CodeISO639_1("ng")
    @Description("Ndonga")
    ndo,
    @CodeISO639_2("nep")
    @CodeISO639_1("ne")
    @Description("Nepali")
    nep,
    @CodeISO639_2("nno")
    @CodeISO639_1("nn")
    @Description("Norwegian Nynorsk")
    nno,
    @CodeISO639_2("nob")
    @CodeISO639_1("nb")
    @Description("Norwegian Bokmal")
    nob,
    @CodeISO639_2("nor")
    @CodeISO639_1("no")
    @Description("Norwegian")
    nor,
    @CodeISO639_2("nya")
    @CodeISO639_1("ny")
    @Description("Chichewa")
    nya,
    @CodeISO639_2("oci")
    @CodeISO639_1("oc")
    @Description("Occitan")
    oci,
    @CodeISO639_2("oji")
    @CodeISO639_1("oj")
    @Description("Ojibwa")
    oji,
    @CodeISO639_2("ori")
    @CodeISO639_1("or")
    @Description("Oriya")
    ori,
    @CodeISO639_2("orm")
    @CodeISO639_1("om")
    @Description("Oromo")
    orm,
    @CodeISO639_2("oss")
    @CodeISO639_1("os")
    @Description("Ossetian")
    oss,
    @CodeISO639_2("pan")
    @CodeISO639_1("pa")
    @Description("Panjabi")
    pan,
    @CodeISO639_2("per")
    @CodeISO639_1("fa")
    @Description("Persian")
    per,
    @CodeISO639_2("pli")
    @CodeISO639_1("pi")
    @Description("Pali")
    pli,
    @CodeISO639_2("pol")
    @CodeISO639_1("pl")
    @Description("Polish")
    pol,
    @CodeISO639_2("por")
    @CodeISO639_1("pt")
    @Description("Portuguese")
    por,
    @CodeISO639_2("pus")
    @CodeISO639_1("ps")
    @Description("Pushto")
    pus,
    @CodeISO639_2("que")
    @CodeISO639_1("qu")
    @Description("Quechua")
    que,
    @CodeISO639_2("roh")
    @CodeISO639_1("rm")
    @Description("Raeto-Romance")
    roh,
    @CodeISO639_2("run")
    @CodeISO639_1("rn")
    @Description("Rundi")
    run,
    @CodeISO639_2("rus")
    @CodeISO639_1("ru")
    @Description("Russian")
    rus,
    @CodeISO639_2("sag")
    @CodeISO639_1("sg")
    @Description("Sango")
    sag,
    @CodeISO639_2("san")
    @CodeISO639_1("sa")
    @Description("Sanskrit")
    san,
    @CodeISO639_2("scc")
    @CodeISO639_1("sr")
    @Description("Serbian")
    scc,
    @CodeISO639_2("sin")
    @CodeISO639_1("si")
    @Description("Sinhalese")
    sin,
    @CodeISO639_2("slo")
    @CodeISO639_1("sk")
    @Description("Slovak")
    slo,
    @CodeISO639_2("slv")
    @CodeISO639_1("sl")
    @Description("Slovenian")
    slv,
    @CodeISO639_2("sme")
    @CodeISO639_1("se")
    @Description("Northern Sami")
    sme,
    @CodeISO639_2("smo")
    @CodeISO639_1("sm")
    @Description("Samoan")
    smo,
    @CodeISO639_2("sna")
    @CodeISO639_1("sn")
    @Description("Shona")
    sna,
    @CodeISO639_2("snd")
    @CodeISO639_1("sd")
    @Description("Sindhi")
    snd,
    @CodeISO639_2("som")
    @CodeISO639_1("so")
    @Description("Somali")
    som,
    @CodeISO639_2("sot")
    @CodeISO639_1("st")
    @Description("Sotho, Southern")
    sot,
    @CodeISO639_2("spa")
    @CodeISO639_1("es")
    @Description("Spanish")
    spa,
    @CodeISO639_2("srd")
    @CodeISO639_1("sc")
    @Description("Sardinian")
    srd,
    @CodeISO639_2("ssw")
    @CodeISO639_1("ss")
    @Description("Swati")
    ssw,
    @CodeISO639_2("sun")
    @CodeISO639_1("su")
    @Description("Sundanese")
    sun,
    @CodeISO639_2("swa")
    @CodeISO639_1("sw")
    @Description("Swahili")
    swa,
    @CodeISO639_2("swe")
    @CodeISO639_1("sv")
    @Description("Swedish")
    swe,
    @CodeISO639_2("tah")
    @CodeISO639_1("ty")
    @Description("Tahitian")
    tah,
    @CodeISO639_2("tam")
    @CodeISO639_1("ta")
    @Description("Tamil")
    tam,
    @CodeISO639_2("tat")
    @CodeISO639_1("tt")
    @Description("Tatar")
    tat,
    @CodeISO639_2("tel")
    @CodeISO639_1("te")
    @Description("Telugu")
    tel,
    @CodeISO639_2("tgk")
    @CodeISO639_1("tg")
    @Description("Tajik")
    tgk,
    @CodeISO639_2("tgl")
    @CodeISO639_1("tl")
    @Description("Tagalog")
    tgl,
    @CodeISO639_2("tha")
    @CodeISO639_1("th")
    @Description("Thai")
    tha,
    @CodeISO639_2("tib")
    @CodeISO639_1("bo")
    @Description("Tibetan")
    tib,
    @CodeISO639_2("tir")
    @CodeISO639_1("ti")
    @Description("Tigrinya")
    tir,
    @CodeISO639_2("ton")
    @CodeISO639_1("to")
    @Description("Tonga (Tonga Islands)")
    ton,
    @CodeISO639_2("tsn")
    @CodeISO639_1("tn")
    @Description("Tswana")
    tsn,
    @CodeISO639_2("tso")
    @CodeISO639_1("ts")
    @Description("Tsonga")
    tso,
    @CodeISO639_2("tuk")
    @CodeISO639_1("tk")
    @Description("Turkmen")
    tuk,
    @CodeISO639_2("tur")
    @CodeISO639_1("tr")
    @Description("Turkish")
    tur,
    @CodeISO639_2("twi")
    @CodeISO639_1("tw")
    @Description("Twi")
    twi,
    @CodeISO639_2("uig")
    @CodeISO639_1("ug")
    @Description("Uighur")
    uig,
    @CodeISO639_2("ukr")
    @CodeISO639_1("uk")
    @Description("Ukrainian")
    ukr,
    @CodeISO639_2("urd")
    @CodeISO639_1("ur")
    @Description("Urdu")
    urd,
    @CodeISO639_2("uzb")
    @CodeISO639_1("uz")
    @Description("Uzbek")
    uzb,
    @CodeISO639_2("ven")
    @CodeISO639_1("ve")
    @Description("Venda")
    ven,
    @CodeISO639_2("vie")
    @CodeISO639_1("vi")
    @Description("Vietnamese")
    vie,
    @CodeISO639_2("vol")
    @CodeISO639_1("vo")
    @Description("VolapÃ¼k")
    vol,
    @CodeISO639_2("wel")
    @CodeISO639_1("cy")
    @Description("Welsh")
    wel,
    @CodeISO639_2("wln")
    @CodeISO639_1("wa")
    @Description("Walloon")
    wln,
    @CodeISO639_2("wol")
    @CodeISO639_1("wo")
    @Description("Wolof")
    wol,
    @CodeISO639_2("xho")
    @CodeISO639_1("xh")
    @Description("Xhosa")
    xho,
    @CodeISO639_2("yid")
    @CodeISO639_1("yi")
    @Description("Yiddish")
    yid,
    @CodeISO639_2("yor")
    @CodeISO639_1("yo")
    @Description("Yoruba")
    yor,
    @CodeISO639_2("zha")
    @CodeISO639_1("za")
    @Description("Zhuang")
    zha,
    @CodeISO639_2("zul")
    @CodeISO639_1("zu")
    @Description("Zulu")
    zul,
    @CodeISO639_2("rum")
    @CodeISO639_1("ro")
    @Description("Romanian")
    rum,
    @CodeISO639_2("pob")
    @CodeSufix({"pob", "pb", "ptbr"})
    @Description("Portuguese - Brazil")
    por_BR,
    @CodeISO639_2("ass")
    @CodeISO639_1("ay")
    @Description("Assyrian")
    ass,
    @CodeISO639_2("chr")
    @Description("Cherokee")
    chr,
    @CodeISO639_2("syc")
    @Description("Classical Syriac")
    syc;

    public static String[] getValues() {
        return getValues(SubTitleLanguage.values());
    }

    public static String[] getValues(SubTitleLanguage[] values) {
        String[] stringValues = new String[values.length];
        for (int j = 0; j < values.length; j++)
            stringValues[j] = values[j].toString();
        return stringValues;
    }

    public static String[] getDescriptions() {
        return getDescriptions(SubTitleLanguage.values());
    }

    public static String[] getDescriptions(SubTitleLanguage[] values) {
        String[] stringValues = new String[values.length];
        for (int j = 0; j < values.length; j++)
            try {
                stringValues[j] = SubTitleLanguage.class.getField(values[j].name()).getAnnotation(Description.class).value();
            } catch (NoSuchFieldException e) {
                throw new RuntimeException(e.getMessage(), e);
            }
        return stringValues;
    }

    public static String getCodeISO639_2(SubTitleLanguage subTitleLanguage) {
        try {
            return SubTitleLanguage.class.getField(subTitleLanguage.name()).getAnnotation(CodeISO639_2.class).value();
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }

    public static String[] getCodeSufix(SubTitleLanguage subTitleLanguage) {
        try {
            String[] value = SubTitleLanguage.class.getField(subTitleLanguage.name()).getAnnotation(CodeSufix.class).value();
            if (value.length == 0) {
                value = new String[1];
                value[0] = getCodeISO639_2(subTitleLanguage);
            }
            return value;
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }
}
