/*
Useful functions:

    loadScript( abs_path )       - load script from an absolute location on your computer
    loadPluginScript( rel_path ) - load script from file within the plugin directory
    
    DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN ON PLUGIN UPDATE 
*/


var vuzeimports = 
	new JavaImporter( 
		org.gudy.azureus2.plugins, 
		org.gudy.azureus2.plugins.config, 
		org.gudy.azureus2.plugins.ddb, 
		org.gudy.azureus2.plugins.disk, 
		org.gudy.azureus2.plugins.download, 
		org.gudy.azureus2.plugins.download.savelocation, 
		org.gudy.azureus2.plugins.ipfilter, 
		org.gudy.azureus2.plugins.logging, 
		org.gudy.azureus2.plugins.network, 
		org.gudy.azureus2.plugins.peers, 
		org.gudy.azureus2.plugins.platform, 
		org.gudy.azureus2.plugins.sharing, 
		org.gudy.azureus2.plugins.tag, 
		org.gudy.azureus2.plugins.torrent, 
		org.gudy.azureus2.plugins.tracker, 
		org.gudy.azureus2.plugins.tracker.web, 
		org.gudy.azureus2.plugins.utils,
		org.gudy.azureus2.plugins.utils.resourcedownloader,
		org.gudy.azureus2.plugins.utils.resourceuploader,
		org.gudy.azureus2.plugins.utils.search,
		org.gudy.azureus2.plugins.utils.security,
		org.gudy.azureus2.plugins.utils.subscriptions,
		org.gudy.azureus2.plugins.utils.xml,
		org.gudy.azureus2.plugins.utils.xml.rss,
		org.gudy.azureus2.plugins.utils.xml.simpleparser );
	


print( "Loaded init.js" );